### ISSUE TITLE
grafana-cli install shows not found error

### ISSUE THREAD

**Issue by blackavec** [grafana/google-bigquery-datasource#119]
hi, i try to install this by 
```
grafana-cli plugins install grafana-bigquery-datasource
```
but it shows me this:
```
Error: ✗ Failed to find requested plugin, check if the plugin_id is correct: 404 not found error

NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>

USAGE:
   Grafana cli plugins install [arguments...]
```

i'm running this command on docker container

**Comment by blackavec** [comment]
this is also how i run the grafana on docker-compose:
```
  grafana:
    image: grafana/grafana:6.5.0
    volumes:
      - ~/.config/gcloud/:/root/.config/gcloud
      - .grafana:/var/lib/grafana
    environment:
      - "GF_INSTALL_PLUGINS=doitintl-bigquery-datasource"
      - "GF_SECURITY_ADMIN_USER=****"
      - "GF_SECURITY_ADMIN_PASSWORD=******"
      - "GF_SECURITY_DISABLE_GRAVATAR=true"
    ports:
      - 3000:3000

```
